# Generated by Django 4.2 on 2023-04-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = []
